version: 1.0.{build}-{branch}

shallow_clone: true

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      TOOLSET: msvc-14.1
      ARCH: x86_64

install:

build: off

test_script:
  - set PATH=%ADDPATH%%PATH%
  - |-
    echo using zlib : : include\include search\lib ; > config.jam
    more config.jam
    
